version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-235-68-3.compute-1.amazonaws.com
            port: '5432'
            database: dag3o52hmkn3gr
            # schema: # this property is not needed.
            ssl: true # ssl property is req'ed. even if you
            # answer the question for ssl yes in the beginning when setting up prisma in this
            # version of docker it does not automatically place the ssl property so you
            # need to add the ssl property which is req'ed for heroku. 
            user: hcusgpizwkeqjf
            password: 9237f530f00b74de139df7127d177e1ee837a2290381b668731662488580d20a
            migrations: true
